name: Simulated Security Alert Pipeline

on:
  workflow_dispatch:

jobs:
  simulate-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Brute Force Alert Telemetry
        run: |
          echo "Simulating 100+ failed login attempts..."
          
      - name: Send Alert to Tines SOAR Engine
        run: |
          curl -X POST "https://shy-sunset-8441.tines.com/webhook/your-first-story-2/10cb269cf8f6791302a262ea1722d698" -d '{"event_type": "Brute Force Attack Detected", "severity": "HIGH", "target_host": "Ubuntu-Server-01", "source_ip": "192.168.1.45"}'
